// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"bytes"
	"fmt"
	"io"
	"strconv"
)

type AuthenticatedUser struct {
	UserID   string   `json:"userId"`
	AuthType AuthType `json:"authType"`
	Token    string   `json:"token"`
}

type CompleteAuthInput struct {
	SessionID string `json:"sessionId"`
	Phone     string `json:"phone"`
}

type Mutation struct {
}

type OtpInput struct {
	SessionID string `json:"sessionId"`
	Otp       string `json:"otp"`
}

type Query struct {
}

type Session struct {
	SessionID string `json:"sessionId"`
}

type AuthType string

const (
	AuthTypeNewUser      AuthType = "NEW_USER"
	AuthTypeExistingUser AuthType = "EXISTING_USER"
)

var AllAuthType = []AuthType{
	AuthTypeNewUser,
	AuthTypeExistingUser,
}

func (e AuthType) IsValid() bool {
	switch e {
	case AuthTypeNewUser, AuthTypeExistingUser:
		return true
	}
	return false
}

func (e AuthType) String() string {
	return string(e)
}

func (e *AuthType) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = AuthType(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid AuthType", str)
	}
	return nil
}

func (e AuthType) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *AuthType) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e AuthType) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type OtpValidityStatus string

const (
	OtpValidityStatusValid   OtpValidityStatus = "VALID"
	OtpValidityStatusInvalid OtpValidityStatus = "INVALID"
	OtpValidityStatusExpired OtpValidityStatus = "EXPIRED"
)

var AllOtpValidityStatus = []OtpValidityStatus{
	OtpValidityStatusValid,
	OtpValidityStatusInvalid,
	OtpValidityStatusExpired,
}

func (e OtpValidityStatus) IsValid() bool {
	switch e {
	case OtpValidityStatusValid, OtpValidityStatusInvalid, OtpValidityStatusExpired:
		return true
	}
	return false
}

func (e OtpValidityStatus) String() string {
	return string(e)
}

func (e *OtpValidityStatus) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = OtpValidityStatus(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid OtpValidityStatus", str)
	}
	return nil
}

func (e OtpValidityStatus) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *OtpValidityStatus) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e OtpValidityStatus) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}
