// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"bytes"
	"fmt"
	"io"
	"strconv"
)

type AttachmentInfo struct {
	AttachmentID string `json:"attachmentId"`
}

type AuthenticatedUser struct {
	UserID   string   `json:"userId"`
	AuthType AuthType `json:"authType"`
	Token    string   `json:"token"`
}

type CompleteAuthInput struct {
	SessionID string `json:"sessionId"`
	Phone     string `json:"phone"`
}

type FileInfo struct {
	Name     string         `json:"name"`
	Size     int32          `json:"size"`
	MimeType string         `json:"mimeType"`
	Kind     AttachmentKind `json:"kind"`
}

type Mutation struct {
}

type OtpInput struct {
	SessionID string `json:"sessionId"`
	Otp       string `json:"otp"`
}

type PresignedFileInfo struct {
	Name     string         `json:"name"`
	MimeType string         `json:"mimeType"`
	FileKey  string         `json:"fileKey"`
	Kind     AttachmentKind `json:"kind"`
}

type PublicKeyInput struct {
	Algorithm string `json:"algorithm"`
	PublicKey string `json:"publicKey"`
	UserToken string `json:"userToken"`
}

type Query struct {
}

type ResendOtpInput struct {
	SessionID string `json:"sessionId"`
	Phone     string `json:"phone"`
}

type Session struct {
	SessionID string `json:"sessionId"`
}

type SignedURLInfo struct {
	UploadURI string `json:"uploadUri"`
	FileKey   string `json:"fileKey"`
}

type User struct {
	UserID      string  `json:"userId"`
	Phone       string  `json:"phone"`
	DisplayName *string `json:"displayName,omitempty"`
	CreatedAt   string  `json:"createdAt"`
	StatusText  *string `json:"statusText,omitempty"`
	PictureURL  *string `json:"pictureUrl,omitempty"`
}

type AttachmentKind string

const (
	AttachmentKindImage    AttachmentKind = "IMAGE"
	AttachmentKindVideo    AttachmentKind = "VIDEO"
	AttachmentKindDocument AttachmentKind = "DOCUMENT"
)

var AllAttachmentKind = []AttachmentKind{
	AttachmentKindImage,
	AttachmentKindVideo,
	AttachmentKindDocument,
}

func (e AttachmentKind) IsValid() bool {
	switch e {
	case AttachmentKindImage, AttachmentKindVideo, AttachmentKindDocument:
		return true
	}
	return false
}

func (e AttachmentKind) String() string {
	return string(e)
}

func (e *AttachmentKind) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = AttachmentKind(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid AttachmentKind", str)
	}
	return nil
}

func (e AttachmentKind) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *AttachmentKind) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e AttachmentKind) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type AuthType string

const (
	AuthTypeNew      AuthType = "NEW"
	AuthTypeExisting AuthType = "EXISTING"
)

var AllAuthType = []AuthType{
	AuthTypeNew,
	AuthTypeExisting,
}

func (e AuthType) IsValid() bool {
	switch e {
	case AuthTypeNew, AuthTypeExisting:
		return true
	}
	return false
}

func (e AuthType) String() string {
	return string(e)
}

func (e *AuthType) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = AuthType(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid AuthType", str)
	}
	return nil
}

func (e AuthType) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *AuthType) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e AuthType) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type OtpValidityStatus string

const (
	OtpValidityStatusValid   OtpValidityStatus = "VALID"
	OtpValidityStatusInvalid OtpValidityStatus = "INVALID"
	OtpValidityStatusExpired OtpValidityStatus = "EXPIRED"
)

var AllOtpValidityStatus = []OtpValidityStatus{
	OtpValidityStatusValid,
	OtpValidityStatusInvalid,
	OtpValidityStatusExpired,
}

func (e OtpValidityStatus) IsValid() bool {
	switch e {
	case OtpValidityStatusValid, OtpValidityStatusInvalid, OtpValidityStatusExpired:
		return true
	}
	return false
}

func (e OtpValidityStatus) String() string {
	return string(e)
}

func (e *OtpValidityStatus) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = OtpValidityStatus(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid OtpValidityStatus", str)
	}
	return nil
}

func (e OtpValidityStatus) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *OtpValidityStatus) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e OtpValidityStatus) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}
