// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.1
// source: proto/attachment.proto

package attachmentpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AttachmentKind int32

const (
	AttachmentKind_ATTACHMENT_KIND_UNSPECIFIED AttachmentKind = 0
	AttachmentKind_ATTACHMENT_KIND_IMAGE       AttachmentKind = 1
	AttachmentKind_ATTACHMENT_KIND_VIDEO       AttachmentKind = 2
	AttachmentKind_ATTACHMENT_KIND_DOCUMENT    AttachmentKind = 3
)

// Enum value maps for AttachmentKind.
var (
	AttachmentKind_name = map[int32]string{
		0: "ATTACHMENT_KIND_UNSPECIFIED",
		1: "ATTACHMENT_KIND_IMAGE",
		2: "ATTACHMENT_KIND_VIDEO",
		3: "ATTACHMENT_KIND_DOCUMENT",
	}
	AttachmentKind_value = map[string]int32{
		"ATTACHMENT_KIND_UNSPECIFIED": 0,
		"ATTACHMENT_KIND_IMAGE":       1,
		"ATTACHMENT_KIND_VIDEO":       2,
		"ATTACHMENT_KIND_DOCUMENT":    3,
	}
)

func (x AttachmentKind) Enum() *AttachmentKind {
	p := new(AttachmentKind)
	*p = x
	return p
}

func (x AttachmentKind) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AttachmentKind) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_attachment_proto_enumTypes[0].Descriptor()
}

func (AttachmentKind) Type() protoreflect.EnumType {
	return &file_proto_attachment_proto_enumTypes[0]
}

func (x AttachmentKind) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AttachmentKind.Descriptor instead.
func (AttachmentKind) EnumDescriptor() ([]byte, []int) {
	return file_proto_attachment_proto_rawDescGZIP(), []int{0}
}

type GetSignedURIRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Size          uint64                 `protobuf:"varint,2,opt,name=size,proto3" json:"size,omitempty"`
	MimeType      string                 `protobuf:"bytes,3,opt,name=mime_type,json=mimeType,proto3" json:"mime_type,omitempty"`
	Kind          AttachmentKind         `protobuf:"varint,4,opt,name=kind,proto3,enum=chat.AttachmentKind" json:"kind,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSignedURIRequest) Reset() {
	*x = GetSignedURIRequest{}
	mi := &file_proto_attachment_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSignedURIRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSignedURIRequest) ProtoMessage() {}

func (x *GetSignedURIRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_attachment_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSignedURIRequest.ProtoReflect.Descriptor instead.
func (*GetSignedURIRequest) Descriptor() ([]byte, []int) {
	return file_proto_attachment_proto_rawDescGZIP(), []int{0}
}

func (x *GetSignedURIRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *GetSignedURIRequest) GetSize() uint64 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *GetSignedURIRequest) GetMimeType() string {
	if x != nil {
		return x.MimeType
	}
	return ""
}

func (x *GetSignedURIRequest) GetKind() AttachmentKind {
	if x != nil {
		return x.Kind
	}
	return AttachmentKind_ATTACHMENT_KIND_UNSPECIFIED
}

type GetSignedURIResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UploadUri     string                 `protobuf:"bytes,1,opt,name=upload_uri,json=uploadUri,proto3" json:"upload_uri,omitempty"`
	FileKey       string                 `protobuf:"bytes,2,opt,name=file_key,json=fileKey,proto3" json:"file_key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSignedURIResponse) Reset() {
	*x = GetSignedURIResponse{}
	mi := &file_proto_attachment_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSignedURIResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSignedURIResponse) ProtoMessage() {}

func (x *GetSignedURIResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_attachment_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSignedURIResponse.ProtoReflect.Descriptor instead.
func (*GetSignedURIResponse) Descriptor() ([]byte, []int) {
	return file_proto_attachment_proto_rawDescGZIP(), []int{1}
}

func (x *GetSignedURIResponse) GetUploadUri() string {
	if x != nil {
		return x.UploadUri
	}
	return ""
}

func (x *GetSignedURIResponse) GetFileKey() string {
	if x != nil {
		return x.FileKey
	}
	return ""
}

type UploadFileRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	MimeType      string                 `protobuf:"bytes,2,opt,name=mime_type,json=mimeType,proto3" json:"mime_type,omitempty"`
	FileKey       string                 `protobuf:"bytes,3,opt,name=file_key,json=fileKey,proto3" json:"file_key,omitempty"`
	Kind          AttachmentKind         `protobuf:"varint,4,opt,name=kind,proto3,enum=chat.AttachmentKind" json:"kind,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadFileRequest) Reset() {
	*x = UploadFileRequest{}
	mi := &file_proto_attachment_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadFileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadFileRequest) ProtoMessage() {}

func (x *UploadFileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_attachment_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadFileRequest.ProtoReflect.Descriptor instead.
func (*UploadFileRequest) Descriptor() ([]byte, []int) {
	return file_proto_attachment_proto_rawDescGZIP(), []int{2}
}

func (x *UploadFileRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UploadFileRequest) GetMimeType() string {
	if x != nil {
		return x.MimeType
	}
	return ""
}

func (x *UploadFileRequest) GetFileKey() string {
	if x != nil {
		return x.FileKey
	}
	return ""
}

func (x *UploadFileRequest) GetKind() AttachmentKind {
	if x != nil {
		return x.Kind
	}
	return AttachmentKind_ATTACHMENT_KIND_UNSPECIFIED
}

type UploadFileResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AttachmentId  string                 `protobuf:"bytes,1,opt,name=attachment_id,json=attachmentId,proto3" json:"attachment_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadFileResponse) Reset() {
	*x = UploadFileResponse{}
	mi := &file_proto_attachment_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadFileResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadFileResponse) ProtoMessage() {}

func (x *UploadFileResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_attachment_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadFileResponse.ProtoReflect.Descriptor instead.
func (*UploadFileResponse) Descriptor() ([]byte, []int) {
	return file_proto_attachment_proto_rawDescGZIP(), []int{3}
}

func (x *UploadFileResponse) GetAttachmentId() string {
	if x != nil {
		return x.AttachmentId
	}
	return ""
}

var File_proto_attachment_proto protoreflect.FileDescriptor

const file_proto_attachment_proto_rawDesc = "" +
	"\n" +
	"\x16proto/attachment.proto\x12\x04chat\"\x84\x01\n" +
	"\x13GetSignedURIRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x12\n" +
	"\x04size\x18\x02 \x01(\x04R\x04size\x12\x1b\n" +
	"\tmime_type\x18\x03 \x01(\tR\bmimeType\x12(\n" +
	"\x04kind\x18\x04 \x01(\x0e2\x14.chat.AttachmentKindR\x04kind\"P\n" +
	"\x14GetSignedURIResponse\x12\x1d\n" +
	"\n" +
	"upload_uri\x18\x01 \x01(\tR\tuploadUri\x12\x19\n" +
	"\bfile_key\x18\x02 \x01(\tR\afileKey\"\x89\x01\n" +
	"\x11UploadFileRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1b\n" +
	"\tmime_type\x18\x02 \x01(\tR\bmimeType\x12\x19\n" +
	"\bfile_key\x18\x03 \x01(\tR\afileKey\x12(\n" +
	"\x04kind\x18\x04 \x01(\x0e2\x14.chat.AttachmentKindR\x04kind\"9\n" +
	"\x12UploadFileResponse\x12#\n" +
	"\rattachment_id\x18\x01 \x01(\tR\fattachmentId*\x85\x01\n" +
	"\x0eAttachmentKind\x12\x1f\n" +
	"\x1bATTACHMENT_KIND_UNSPECIFIED\x10\x00\x12\x19\n" +
	"\x15ATTACHMENT_KIND_IMAGE\x10\x01\x12\x19\n" +
	"\x15ATTACHMENT_KIND_VIDEO\x10\x02\x12\x1c\n" +
	"\x18ATTACHMENT_KIND_DOCUMENT\x10\x032\x9b\x01\n" +
	"\x11AttachmentService\x12E\n" +
	"\fGetSignedURI\x12\x19.chat.GetSignedURIRequest\x1a\x1a.chat.GetSignedURIResponse\x12?\n" +
	"\n" +
	"UploadFile\x12\x17.chat.UploadFileRequest\x1a\x18.chat.UploadFileResponseB@Z>github.com/Dev-Siri/sero/backend/proto/attachment;attachmentpbb\x06proto3"

var (
	file_proto_attachment_proto_rawDescOnce sync.Once
	file_proto_attachment_proto_rawDescData []byte
)

func file_proto_attachment_proto_rawDescGZIP() []byte {
	file_proto_attachment_proto_rawDescOnce.Do(func() {
		file_proto_attachment_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_attachment_proto_rawDesc), len(file_proto_attachment_proto_rawDesc)))
	})
	return file_proto_attachment_proto_rawDescData
}

var file_proto_attachment_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proto_attachment_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_proto_attachment_proto_goTypes = []any{
	(AttachmentKind)(0),          // 0: chat.AttachmentKind
	(*GetSignedURIRequest)(nil),  // 1: chat.GetSignedURIRequest
	(*GetSignedURIResponse)(nil), // 2: chat.GetSignedURIResponse
	(*UploadFileRequest)(nil),    // 3: chat.UploadFileRequest
	(*UploadFileResponse)(nil),   // 4: chat.UploadFileResponse
}
var file_proto_attachment_proto_depIdxs = []int32{
	0, // 0: chat.GetSignedURIRequest.kind:type_name -> chat.AttachmentKind
	0, // 1: chat.UploadFileRequest.kind:type_name -> chat.AttachmentKind
	1, // 2: chat.AttachmentService.GetSignedURI:input_type -> chat.GetSignedURIRequest
	3, // 3: chat.AttachmentService.UploadFile:input_type -> chat.UploadFileRequest
	2, // 4: chat.AttachmentService.GetSignedURI:output_type -> chat.GetSignedURIResponse
	4, // 5: chat.AttachmentService.UploadFile:output_type -> chat.UploadFileResponse
	4, // [4:6] is the sub-list for method output_type
	2, // [2:4] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_proto_attachment_proto_init() }
func file_proto_attachment_proto_init() {
	if File_proto_attachment_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_attachment_proto_rawDesc), len(file_proto_attachment_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_attachment_proto_goTypes,
		DependencyIndexes: file_proto_attachment_proto_depIdxs,
		EnumInfos:         file_proto_attachment_proto_enumTypes,
		MessageInfos:      file_proto_attachment_proto_msgTypes,
	}.Build()
	File_proto_attachment_proto = out.File
	file_proto_attachment_proto_goTypes = nil
	file_proto_attachment_proto_depIdxs = nil
}
