package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.84

import (
	"context"

	"github.com/Dev-Siri/sero/backend/proto/attachmentpb"
	"github.com/Dev-Siri/sero/backend/services/gateway/graph/model"
	"github.com/Dev-Siri/sero/backend/services/gateway/types"
	"github.com/Dev-Siri/sero/backend/shared/logging"
	"go.uber.org/zap"
)

// UploadFile is the resolver for the uploadFile field.
func (r *mutationResolver) UploadFile(ctx context.Context, presignedFileInfo model.PresignedFileInfo) (*model.AttachmentInfo, error) {
	uploadResponse, err := r.AttachmentService.UploadFile(ctx, &attachmentpb.UploadFileRequest{
		Name:     presignedFileInfo.Name,
		FileKey:  presignedFileInfo.FileKey,
		MimeType: presignedFileInfo.MimeType,
		Kind:     types.AttachmentKindGqlToGrpcEnumMap[presignedFileInfo.Kind],
	})
	if err != nil {
		logging.Logger.Error("resolver 'UploadFile' errored.", zap.Error(err))
		return nil, err
	}

	return &model.AttachmentInfo{
		AttachmentID: uploadResponse.AttachmentId,
	}, nil
}

// GetSignedURL is the resolver for the getSignedUrl field.
func (r *queryResolver) GetSignedURL(ctx context.Context, fileInfo model.FileInfo) (*model.SignedURLInfo, error) {
	signedURIResponse, err := r.AttachmentService.GetSignedURI(ctx, &attachmentpb.GetSignedURIRequest{
		Name:     fileInfo.Name,
		Size:     uint64(fileInfo.Size),
		MimeType: fileInfo.MimeType,
		Kind:     types.AttachmentKindGqlToGrpcEnumMap[fileInfo.Kind],
	})
	if err != nil {
		logging.Logger.Error("resolver 'GetSignedURL' errored.", zap.Error(err))
		return nil, err
	}

	return &model.SignedURLInfo{
		UploadURI: signedURIResponse.UploadUri,
		FileKey:   signedURIResponse.FileKey,
	}, nil
}
