// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package graph

import (
	"context"
	"errors"
	"strconv"
	"sync/atomic"

	"github.com/99designs/gqlgen/graphql"
	"github.com/Dev-Siri/sero/backend/services/gateway/graph/model"
	"github.com/vektah/gqlparser/v2/ast"
)

// region    ************************** generated!.gotpl **************************

// endregion ************************** generated!.gotpl **************************

// region    ***************************** args.gotpl *****************************

// endregion ***************************** args.gotpl *****************************

// region    ************************** directives.gotpl **************************

// endregion ************************** directives.gotpl **************************

// region    **************************** field.gotpl *****************************

func (ec *executionContext) _AttachmentInfo_attachmentId(ctx context.Context, field graphql.CollectedField, obj *model.AttachmentInfo) (ret graphql.Marshaler) {
	return graphql.ResolveField(
		ctx,
		ec.OperationContext,
		field,
		ec.fieldContext_AttachmentInfo_attachmentId,
		func(ctx context.Context) (any, error) {
			return obj.AttachmentID, nil
		},
		nil,
		ec.marshalNString2string,
		true,
		true,
	)
}

func (ec *executionContext) fieldContext_AttachmentInfo_attachmentId(_ context.Context, field graphql.CollectedField) (fc *graphql.FieldContext, err error) {
	fc = &graphql.FieldContext{
		Object:     "AttachmentInfo",
		Field:      field,
		IsMethod:   false,
		IsResolver: false,
		Child: func(ctx context.Context, field graphql.CollectedField) (*graphql.FieldContext, error) {
			return nil, errors.New("field of type String does not have child fields")
		},
	}
	return fc, nil
}

func (ec *executionContext) _SignedUrlInfo_uploadUri(ctx context.Context, field graphql.CollectedField, obj *model.SignedURLInfo) (ret graphql.Marshaler) {
	return graphql.ResolveField(
		ctx,
		ec.OperationContext,
		field,
		ec.fieldContext_SignedUrlInfo_uploadUri,
		func(ctx context.Context) (any, error) {
			return obj.UploadURI, nil
		},
		nil,
		ec.marshalNString2string,
		true,
		true,
	)
}

func (ec *executionContext) fieldContext_SignedUrlInfo_uploadUri(_ context.Context, field graphql.CollectedField) (fc *graphql.FieldContext, err error) {
	fc = &graphql.FieldContext{
		Object:     "SignedUrlInfo",
		Field:      field,
		IsMethod:   false,
		IsResolver: false,
		Child: func(ctx context.Context, field graphql.CollectedField) (*graphql.FieldContext, error) {
			return nil, errors.New("field of type String does not have child fields")
		},
	}
	return fc, nil
}

func (ec *executionContext) _SignedUrlInfo_fileKey(ctx context.Context, field graphql.CollectedField, obj *model.SignedURLInfo) (ret graphql.Marshaler) {
	return graphql.ResolveField(
		ctx,
		ec.OperationContext,
		field,
		ec.fieldContext_SignedUrlInfo_fileKey,
		func(ctx context.Context) (any, error) {
			return obj.FileKey, nil
		},
		nil,
		ec.marshalNString2string,
		true,
		true,
	)
}

func (ec *executionContext) fieldContext_SignedUrlInfo_fileKey(_ context.Context, field graphql.CollectedField) (fc *graphql.FieldContext, err error) {
	fc = &graphql.FieldContext{
		Object:     "SignedUrlInfo",
		Field:      field,
		IsMethod:   false,
		IsResolver: false,
		Child: func(ctx context.Context, field graphql.CollectedField) (*graphql.FieldContext, error) {
			return nil, errors.New("field of type String does not have child fields")
		},
	}
	return fc, nil
}

// endregion **************************** field.gotpl *****************************

// region    **************************** input.gotpl *****************************

func (ec *executionContext) unmarshalInputFileInfo(ctx context.Context, obj any) (model.FileInfo, error) {
	var it model.FileInfo
	asMap := map[string]any{}
	for k, v := range obj.(map[string]any) {
		asMap[k] = v
	}

	fieldsInOrder := [...]string{"name", "size", "mimeType", "kind"}
	for _, k := range fieldsInOrder {
		v, ok := asMap[k]
		if !ok {
			continue
		}
		switch k {
		case "name":
			ctx := graphql.WithPathContext(ctx, graphql.NewPathWithField("name"))
			data, err := ec.unmarshalNString2string(ctx, v)
			if err != nil {
				return it, err
			}
			it.Name = data
		case "size":
			ctx := graphql.WithPathContext(ctx, graphql.NewPathWithField("size"))
			data, err := ec.unmarshalNInt2int32(ctx, v)
			if err != nil {
				return it, err
			}
			it.Size = data
		case "mimeType":
			ctx := graphql.WithPathContext(ctx, graphql.NewPathWithField("mimeType"))
			data, err := ec.unmarshalNString2string(ctx, v)
			if err != nil {
				return it, err
			}
			it.MimeType = data
		case "kind":
			ctx := graphql.WithPathContext(ctx, graphql.NewPathWithField("kind"))
			data, err := ec.unmarshalNAttachmentKind2githubᚗcomᚋDevᚑSiriᚋseroᚋbackendᚋservicesᚋgatewayᚋgraphᚋmodelᚐAttachmentKind(ctx, v)
			if err != nil {
				return it, err
			}
			it.Kind = data
		}
	}

	return it, nil
}

func (ec *executionContext) unmarshalInputPresignedFileInfo(ctx context.Context, obj any) (model.PresignedFileInfo, error) {
	var it model.PresignedFileInfo
	asMap := map[string]any{}
	for k, v := range obj.(map[string]any) {
		asMap[k] = v
	}

	fieldsInOrder := [...]string{"name", "mimeType", "fileKey", "kind"}
	for _, k := range fieldsInOrder {
		v, ok := asMap[k]
		if !ok {
			continue
		}
		switch k {
		case "name":
			ctx := graphql.WithPathContext(ctx, graphql.NewPathWithField("name"))
			data, err := ec.unmarshalNString2string(ctx, v)
			if err != nil {
				return it, err
			}
			it.Name = data
		case "mimeType":
			ctx := graphql.WithPathContext(ctx, graphql.NewPathWithField("mimeType"))
			data, err := ec.unmarshalNString2string(ctx, v)
			if err != nil {
				return it, err
			}
			it.MimeType = data
		case "fileKey":
			ctx := graphql.WithPathContext(ctx, graphql.NewPathWithField("fileKey"))
			data, err := ec.unmarshalNString2string(ctx, v)
			if err != nil {
				return it, err
			}
			it.FileKey = data
		case "kind":
			ctx := graphql.WithPathContext(ctx, graphql.NewPathWithField("kind"))
			data, err := ec.unmarshalNAttachmentKind2githubᚗcomᚋDevᚑSiriᚋseroᚋbackendᚋservicesᚋgatewayᚋgraphᚋmodelᚐAttachmentKind(ctx, v)
			if err != nil {
				return it, err
			}
			it.Kind = data
		}
	}

	return it, nil
}

// endregion **************************** input.gotpl *****************************

// region    ************************** interface.gotpl ***************************

// endregion ************************** interface.gotpl ***************************

// region    **************************** object.gotpl ****************************

var attachmentInfoImplementors = []string{"AttachmentInfo"}

func (ec *executionContext) _AttachmentInfo(ctx context.Context, sel ast.SelectionSet, obj *model.AttachmentInfo) graphql.Marshaler {
	fields := graphql.CollectFields(ec.OperationContext, sel, attachmentInfoImplementors)

	out := graphql.NewFieldSet(fields)
	deferred := make(map[string]*graphql.FieldSet)
	for i, field := range fields {
		switch field.Name {
		case "__typename":
			out.Values[i] = graphql.MarshalString("AttachmentInfo")
		case "attachmentId":
			out.Values[i] = ec._AttachmentInfo_attachmentId(ctx, field, obj)
			if out.Values[i] == graphql.Null {
				out.Invalids++
			}
		default:
			panic("unknown field " + strconv.Quote(field.Name))
		}
	}
	out.Dispatch(ctx)
	if out.Invalids > 0 {
		return graphql.Null
	}

	atomic.AddInt32(&ec.deferred, int32(len(deferred)))

	for label, dfs := range deferred {
		ec.processDeferredGroup(graphql.DeferredGroup{
			Label:    label,
			Path:     graphql.GetPath(ctx),
			FieldSet: dfs,
			Context:  ctx,
		})
	}

	return out
}

var signedUrlInfoImplementors = []string{"SignedUrlInfo"}

func (ec *executionContext) _SignedUrlInfo(ctx context.Context, sel ast.SelectionSet, obj *model.SignedURLInfo) graphql.Marshaler {
	fields := graphql.CollectFields(ec.OperationContext, sel, signedUrlInfoImplementors)

	out := graphql.NewFieldSet(fields)
	deferred := make(map[string]*graphql.FieldSet)
	for i, field := range fields {
		switch field.Name {
		case "__typename":
			out.Values[i] = graphql.MarshalString("SignedUrlInfo")
		case "uploadUri":
			out.Values[i] = ec._SignedUrlInfo_uploadUri(ctx, field, obj)
			if out.Values[i] == graphql.Null {
				out.Invalids++
			}
		case "fileKey":
			out.Values[i] = ec._SignedUrlInfo_fileKey(ctx, field, obj)
			if out.Values[i] == graphql.Null {
				out.Invalids++
			}
		default:
			panic("unknown field " + strconv.Quote(field.Name))
		}
	}
	out.Dispatch(ctx)
	if out.Invalids > 0 {
		return graphql.Null
	}

	atomic.AddInt32(&ec.deferred, int32(len(deferred)))

	for label, dfs := range deferred {
		ec.processDeferredGroup(graphql.DeferredGroup{
			Label:    label,
			Path:     graphql.GetPath(ctx),
			FieldSet: dfs,
			Context:  ctx,
		})
	}

	return out
}

// endregion **************************** object.gotpl ****************************

// region    ***************************** type.gotpl *****************************

func (ec *executionContext) marshalNAttachmentInfo2githubᚗcomᚋDevᚑSiriᚋseroᚋbackendᚋservicesᚋgatewayᚋgraphᚋmodelᚐAttachmentInfo(ctx context.Context, sel ast.SelectionSet, v model.AttachmentInfo) graphql.Marshaler {
	return ec._AttachmentInfo(ctx, sel, &v)
}

func (ec *executionContext) marshalNAttachmentInfo2ᚖgithubᚗcomᚋDevᚑSiriᚋseroᚋbackendᚋservicesᚋgatewayᚋgraphᚋmodelᚐAttachmentInfo(ctx context.Context, sel ast.SelectionSet, v *model.AttachmentInfo) graphql.Marshaler {
	if v == nil {
		if !graphql.HasFieldError(ctx, graphql.GetFieldContext(ctx)) {
			graphql.AddErrorf(ctx, "the requested element is null which the schema does not allow")
		}
		return graphql.Null
	}
	return ec._AttachmentInfo(ctx, sel, v)
}

func (ec *executionContext) unmarshalNAttachmentKind2githubᚗcomᚋDevᚑSiriᚋseroᚋbackendᚋservicesᚋgatewayᚋgraphᚋmodelᚐAttachmentKind(ctx context.Context, v any) (model.AttachmentKind, error) {
	var res model.AttachmentKind
	err := res.UnmarshalGQL(v)
	return res, graphql.ErrorOnPath(ctx, err)
}

func (ec *executionContext) marshalNAttachmentKind2githubᚗcomᚋDevᚑSiriᚋseroᚋbackendᚋservicesᚋgatewayᚋgraphᚋmodelᚐAttachmentKind(ctx context.Context, sel ast.SelectionSet, v model.AttachmentKind) graphql.Marshaler {
	return v
}

func (ec *executionContext) unmarshalNFileInfo2githubᚗcomᚋDevᚑSiriᚋseroᚋbackendᚋservicesᚋgatewayᚋgraphᚋmodelᚐFileInfo(ctx context.Context, v any) (model.FileInfo, error) {
	res, err := ec.unmarshalInputFileInfo(ctx, v)
	return res, graphql.ErrorOnPath(ctx, err)
}

func (ec *executionContext) unmarshalNPresignedFileInfo2githubᚗcomᚋDevᚑSiriᚋseroᚋbackendᚋservicesᚋgatewayᚋgraphᚋmodelᚐPresignedFileInfo(ctx context.Context, v any) (model.PresignedFileInfo, error) {
	res, err := ec.unmarshalInputPresignedFileInfo(ctx, v)
	return res, graphql.ErrorOnPath(ctx, err)
}

func (ec *executionContext) marshalNSignedUrlInfo2githubᚗcomᚋDevᚑSiriᚋseroᚋbackendᚋservicesᚋgatewayᚋgraphᚋmodelᚐSignedURLInfo(ctx context.Context, sel ast.SelectionSet, v model.SignedURLInfo) graphql.Marshaler {
	return ec._SignedUrlInfo(ctx, sel, &v)
}

func (ec *executionContext) marshalNSignedUrlInfo2ᚖgithubᚗcomᚋDevᚑSiriᚋseroᚋbackendᚋservicesᚋgatewayᚋgraphᚋmodelᚐSignedURLInfo(ctx context.Context, sel ast.SelectionSet, v *model.SignedURLInfo) graphql.Marshaler {
	if v == nil {
		if !graphql.HasFieldError(ctx, graphql.GetFieldContext(ctx)) {
			graphql.AddErrorf(ctx, "the requested element is null which the schema does not allow")
		}
		return graphql.Null
	}
	return ec._SignedUrlInfo(ctx, sel, v)
}

// endregion ***************************** type.gotpl *****************************
