package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.84

import (
	"context"

	"github.com/Dev-Siri/sero/backend/proto/chatpb"
	"github.com/Dev-Siri/sero/backend/services/gateway/graph/model"
	"github.com/Dev-Siri/sero/backend/shared/logging"
	"go.uber.org/zap"
)

// CreateRoom is the resolver for the createRoom field.
func (r *mutationResolver) CreateRoom(ctx context.Context, members model.RoomMembers) (*model.RoomNavInfo, error) {
	createRoomResponse, err := r.ChatService.CreateRoom(ctx, &chatpb.CreateRoomRequest{
		SenderId:   members.SenderID,
		ReceiverId: members.ReceiverID,
	})
	if err != nil {
		logging.Logger.Error("resolver 'CreateRoom' errored.", zap.Error(err))
		return nil, err
	}

	return &model.RoomNavInfo{
		RoomID: createRoomResponse.RoomId,
	}, nil
}

// GetUserChatRooms is the resolver for the getUserChatRooms field.
func (r *queryResolver) GetUserChatRooms(ctx context.Context, userID string) ([]*model.ChatRoom, error) {
	roomsResponse, err := r.ChatService.GetUserChatRooms(ctx, &chatpb.GetUserChatRoomsRequest{
		UserId: userID,
	})
	if err != nil {
		logging.Logger.Error("resolver 'GetUserChatRooms' errored.", zap.Error(err))
		return nil, err
	}

	chatRooms := make([]*model.ChatRoom, len(roomsResponse.ChatRooms))
	for _, room := range roomsResponse.ChatRooms {
		chatRoom := &model.ChatRoom{
			RoomID:    room.RoomId,
			CreatedAt: room.CreatedAt,
			Sender: &model.User{
				UserID:      room.Sender.UserId,
				Phone:       room.Sender.Phone,
				DisplayName: room.Sender.DisplayName,
				CreatedAt:   room.Sender.CreatedAt,
				StatusText:  room.Sender.StatusText,
				PictureURL:  room.Sender.PictureUrl,
			},
			Receiver: &model.User{
				UserID:      room.Receiver.UserId,
				Phone:       room.Receiver.Phone,
				DisplayName: room.Receiver.DisplayName,
				CreatedAt:   room.Receiver.CreatedAt,
				StatusText:  room.Receiver.StatusText,
				PictureURL:  room.Receiver.PictureUrl,
			},
		}

		chatRooms = append(chatRooms, chatRoom)
	}

	return chatRooms, nil
}
