package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.84

import (
	"context"
	"fmt"

	"github.com/Dev-Siri/sero/services/gateway/graph/model"
)

// CreateSession is the resolver for the createSession field.
func (r *mutationResolver) CreateSession(ctx context.Context, phone string) (*model.Session, error) {
	panic(fmt.Errorf("not implemented: CreateSession - createSession"))
}

// VerifyOtp is the resolver for the verifyOtp field.
func (r *mutationResolver) VerifyOtp(ctx context.Context, otp model.OtpInput) (model.OtpValidityStatus, error) {
	panic(fmt.Errorf("not implemented: VerifyOtp - verifyOtp"))
}

// CompleteAuth is the resolver for the completeAuth field.
func (r *mutationResolver) CompleteAuth(ctx context.Context, otp model.OtpInput) (*model.Session, error) {
	panic(fmt.Errorf("not implemented: CompleteAuth - completeAuth"))
}

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

type mutationResolver struct{ *Resolver }
