// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.1
// source: proto/auth.proto

package authpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type OtpResponse_OtpValidityStatus int32

const (
	OtpResponse_INVALID_OTP OtpResponse_OtpValidityStatus = 0
	OtpResponse_VALID_OTP   OtpResponse_OtpValidityStatus = 1
	OtpResponse_EXPIRED_OTP OtpResponse_OtpValidityStatus = 2
)

// Enum value maps for OtpResponse_OtpValidityStatus.
var (
	OtpResponse_OtpValidityStatus_name = map[int32]string{
		0: "INVALID_OTP",
		1: "VALID_OTP",
		2: "EXPIRED_OTP",
	}
	OtpResponse_OtpValidityStatus_value = map[string]int32{
		"INVALID_OTP": 0,
		"VALID_OTP":   1,
		"EXPIRED_OTP": 2,
	}
)

func (x OtpResponse_OtpValidityStatus) Enum() *OtpResponse_OtpValidityStatus {
	p := new(OtpResponse_OtpValidityStatus)
	*p = x
	return p
}

func (x OtpResponse_OtpValidityStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (OtpResponse_OtpValidityStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_auth_proto_enumTypes[0].Descriptor()
}

func (OtpResponse_OtpValidityStatus) Type() protoreflect.EnumType {
	return &file_proto_auth_proto_enumTypes[0]
}

func (x OtpResponse_OtpValidityStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use OtpResponse_OtpValidityStatus.Descriptor instead.
func (OtpResponse_OtpValidityStatus) EnumDescriptor() ([]byte, []int) {
	return file_proto_auth_proto_rawDescGZIP(), []int{3, 0}
}

type AuthResponse_AuthType int32

const (
	AuthResponse_NEW_USER      AuthResponse_AuthType = 0
	AuthResponse_EXISTING_USER AuthResponse_AuthType = 1
)

// Enum value maps for AuthResponse_AuthType.
var (
	AuthResponse_AuthType_name = map[int32]string{
		0: "NEW_USER",
		1: "EXISTING_USER",
	}
	AuthResponse_AuthType_value = map[string]int32{
		"NEW_USER":      0,
		"EXISTING_USER": 1,
	}
)

func (x AuthResponse_AuthType) Enum() *AuthResponse_AuthType {
	p := new(AuthResponse_AuthType)
	*p = x
	return p
}

func (x AuthResponse_AuthType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AuthResponse_AuthType) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_auth_proto_enumTypes[1].Descriptor()
}

func (AuthResponse_AuthType) Type() protoreflect.EnumType {
	return &file_proto_auth_proto_enumTypes[1]
}

func (x AuthResponse_AuthType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AuthResponse_AuthType.Descriptor instead.
func (AuthResponse_AuthType) EnumDescriptor() ([]byte, []int) {
	return file_proto_auth_proto_rawDescGZIP(), []int{5, 0}
}

type SessionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SessionResponse) Reset() {
	*x = SessionResponse{}
	mi := &file_proto_auth_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SessionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SessionResponse) ProtoMessage() {}

func (x *SessionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_auth_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SessionResponse.ProtoReflect.Descriptor instead.
func (*SessionResponse) Descriptor() ([]byte, []int) {
	return file_proto_auth_proto_rawDescGZIP(), []int{0}
}

func (x *SessionResponse) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

type SessionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Phone         string                 `protobuf:"bytes,1,opt,name=phone,proto3" json:"phone,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SessionRequest) Reset() {
	*x = SessionRequest{}
	mi := &file_proto_auth_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SessionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SessionRequest) ProtoMessage() {}

func (x *SessionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_auth_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SessionRequest.ProtoReflect.Descriptor instead.
func (*SessionRequest) Descriptor() ([]byte, []int) {
	return file_proto_auth_proto_rawDescGZIP(), []int{1}
}

func (x *SessionRequest) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

type OtpRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Otp           string                 `protobuf:"bytes,2,opt,name=otp,proto3" json:"otp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OtpRequest) Reset() {
	*x = OtpRequest{}
	mi := &file_proto_auth_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OtpRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OtpRequest) ProtoMessage() {}

func (x *OtpRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_auth_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OtpRequest.ProtoReflect.Descriptor instead.
func (*OtpRequest) Descriptor() ([]byte, []int) {
	return file_proto_auth_proto_rawDescGZIP(), []int{2}
}

func (x *OtpRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *OtpRequest) GetOtp() string {
	if x != nil {
		return x.Otp
	}
	return ""
}

type OtpResponse struct {
	state             protoimpl.MessageState        `protogen:"open.v1"`
	OtpValidityStatus OtpResponse_OtpValidityStatus `protobuf:"varint,1,opt,name=otp_validity_status,json=otpValidityStatus,proto3,enum=auth.OtpResponse_OtpValidityStatus" json:"otp_validity_status,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *OtpResponse) Reset() {
	*x = OtpResponse{}
	mi := &file_proto_auth_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OtpResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OtpResponse) ProtoMessage() {}

func (x *OtpResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_auth_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OtpResponse.ProtoReflect.Descriptor instead.
func (*OtpResponse) Descriptor() ([]byte, []int) {
	return file_proto_auth_proto_rawDescGZIP(), []int{3}
}

func (x *OtpResponse) GetOtpValidityStatus() OtpResponse_OtpValidityStatus {
	if x != nil {
		return x.OtpValidityStatus
	}
	return OtpResponse_INVALID_OTP
}

type CompleteAuthRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Phone         string                 `protobuf:"bytes,2,opt,name=phone,proto3" json:"phone,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CompleteAuthRequest) Reset() {
	*x = CompleteAuthRequest{}
	mi := &file_proto_auth_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CompleteAuthRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompleteAuthRequest) ProtoMessage() {}

func (x *CompleteAuthRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_auth_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompleteAuthRequest.ProtoReflect.Descriptor instead.
func (*CompleteAuthRequest) Descriptor() ([]byte, []int) {
	return file_proto_auth_proto_rawDescGZIP(), []int{4}
}

func (x *CompleteAuthRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *CompleteAuthRequest) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

type AuthResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AuthType      AuthResponse_AuthType  `protobuf:"varint,1,opt,name=auth_type,json=authType,proto3,enum=auth.AuthResponse_AuthType" json:"auth_type,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Token         string                 `protobuf:"bytes,3,opt,name=token,proto3" json:"token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuthResponse) Reset() {
	*x = AuthResponse{}
	mi := &file_proto_auth_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthResponse) ProtoMessage() {}

func (x *AuthResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_auth_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthResponse.ProtoReflect.Descriptor instead.
func (*AuthResponse) Descriptor() ([]byte, []int) {
	return file_proto_auth_proto_rawDescGZIP(), []int{5}
}

func (x *AuthResponse) GetAuthType() AuthResponse_AuthType {
	if x != nil {
		return x.AuthType
	}
	return AuthResponse_NEW_USER
}

func (x *AuthResponse) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *AuthResponse) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

type UpdateProfileRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Email         string                 `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateProfileRequest) Reset() {
	*x = UpdateProfileRequest{}
	mi := &file_proto_auth_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateProfileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateProfileRequest) ProtoMessage() {}

func (x *UpdateProfileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_auth_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateProfileRequest.ProtoReflect.Descriptor instead.
func (*UpdateProfileRequest) Descriptor() ([]byte, []int) {
	return file_proto_auth_proto_rawDescGZIP(), []int{6}
}

func (x *UpdateProfileRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *UpdateProfileRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UpdateProfileRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

var File_proto_auth_proto protoreflect.FileDescriptor

const file_proto_auth_proto_rawDesc = "" +
	"\n" +
	"\x10proto/auth.proto\x12\x04auth\x1a\x1bgoogle/protobuf/empty.proto\"0\n" +
	"\x0fSessionResponse\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\"&\n" +
	"\x0eSessionRequest\x12\x14\n" +
	"\x05phone\x18\x01 \x01(\tR\x05phone\"=\n" +
	"\n" +
	"OtpRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x10\n" +
	"\x03otp\x18\x02 \x01(\tR\x03otp\"\xa8\x01\n" +
	"\vOtpResponse\x12S\n" +
	"\x13otp_validity_status\x18\x01 \x01(\x0e2#.auth.OtpResponse.OtpValidityStatusR\x11otpValidityStatus\"D\n" +
	"\x11OtpValidityStatus\x12\x0f\n" +
	"\vINVALID_OTP\x10\x00\x12\r\n" +
	"\tVALID_OTP\x10\x01\x12\x0f\n" +
	"\vEXPIRED_OTP\x10\x02\"J\n" +
	"\x13CompleteAuthRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x14\n" +
	"\x05phone\x18\x02 \x01(\tR\x05phone\"\xa4\x01\n" +
	"\fAuthResponse\x128\n" +
	"\tauth_type\x18\x01 \x01(\x0e2\x1b.auth.AuthResponse.AuthTypeR\bauthType\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x14\n" +
	"\x05token\x18\x03 \x01(\tR\x05token\"+\n" +
	"\bAuthType\x12\f\n" +
	"\bNEW_USER\x10\x00\x12\x11\n" +
	"\rEXISTING_USER\x10\x01\"Y\n" +
	"\x14UpdateProfileRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x14\n" +
	"\x05email\x18\x03 \x01(\tR\x05email2\x81\x02\n" +
	"\vAuthService\x12<\n" +
	"\rCreateSession\x12\x14.auth.SessionRequest\x1a\x15.auth.SessionResponse\x120\n" +
	"\tVerifyOtp\x12\x10.auth.OtpRequest\x1a\x11.auth.OtpResponse\x12=\n" +
	"\fCompleteAuth\x12\x19.auth.CompleteAuthRequest\x1a\x12.auth.AuthResponse\x12C\n" +
	"\rUpdateProfile\x12\x1a.auth.UpdateProfileRequest\x1a\x16.google.protobuf.EmptyB,Z*github.com/Dev-Siri/sero/proto/auth;authpbb\x06proto3"

var (
	file_proto_auth_proto_rawDescOnce sync.Once
	file_proto_auth_proto_rawDescData []byte
)

func file_proto_auth_proto_rawDescGZIP() []byte {
	file_proto_auth_proto_rawDescOnce.Do(func() {
		file_proto_auth_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_auth_proto_rawDesc), len(file_proto_auth_proto_rawDesc)))
	})
	return file_proto_auth_proto_rawDescData
}

var file_proto_auth_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_proto_auth_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_proto_auth_proto_goTypes = []any{
	(OtpResponse_OtpValidityStatus)(0), // 0: auth.OtpResponse.OtpValidityStatus
	(AuthResponse_AuthType)(0),         // 1: auth.AuthResponse.AuthType
	(*SessionResponse)(nil),            // 2: auth.SessionResponse
	(*SessionRequest)(nil),             // 3: auth.SessionRequest
	(*OtpRequest)(nil),                 // 4: auth.OtpRequest
	(*OtpResponse)(nil),                // 5: auth.OtpResponse
	(*CompleteAuthRequest)(nil),        // 6: auth.CompleteAuthRequest
	(*AuthResponse)(nil),               // 7: auth.AuthResponse
	(*UpdateProfileRequest)(nil),       // 8: auth.UpdateProfileRequest
	(*emptypb.Empty)(nil),              // 9: google.protobuf.Empty
}
var file_proto_auth_proto_depIdxs = []int32{
	0, // 0: auth.OtpResponse.otp_validity_status:type_name -> auth.OtpResponse.OtpValidityStatus
	1, // 1: auth.AuthResponse.auth_type:type_name -> auth.AuthResponse.AuthType
	3, // 2: auth.AuthService.CreateSession:input_type -> auth.SessionRequest
	4, // 3: auth.AuthService.VerifyOtp:input_type -> auth.OtpRequest
	6, // 4: auth.AuthService.CompleteAuth:input_type -> auth.CompleteAuthRequest
	8, // 5: auth.AuthService.UpdateProfile:input_type -> auth.UpdateProfileRequest
	2, // 6: auth.AuthService.CreateSession:output_type -> auth.SessionResponse
	5, // 7: auth.AuthService.VerifyOtp:output_type -> auth.OtpResponse
	7, // 8: auth.AuthService.CompleteAuth:output_type -> auth.AuthResponse
	9, // 9: auth.AuthService.UpdateProfile:output_type -> google.protobuf.Empty
	6, // [6:10] is the sub-list for method output_type
	2, // [2:6] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_proto_auth_proto_init() }
func file_proto_auth_proto_init() {
	if File_proto_auth_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_auth_proto_rawDesc), len(file_proto_auth_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_auth_proto_goTypes,
		DependencyIndexes: file_proto_auth_proto_depIdxs,
		EnumInfos:         file_proto_auth_proto_enumTypes,
		MessageInfos:      file_proto_auth_proto_msgTypes,
	}.Build()
	File_proto_auth_proto = out.File
	file_proto_auth_proto_goTypes = nil
	file_proto_auth_proto_depIdxs = nil
}
